# Generated by Django 2.2.6 on 2021-05-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0002_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='way_of_preparing',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
