# Generated by Django 2.2.6 on 2021-05-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0003_recipe_way_of_preparing'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation',
            field=models.TextField(default=1, max_length=2048),
            preserve_default=False,
        ),
    ]
