# Generated by Django 2.2.6 on 2021-05-29 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0004_recipe_preparation'),
        ('jedzonko', '0004_auto_20210526_2027'),
    ]

    operations = [
    ]
