# Generated by Django 2.2.6 on 2021-05-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0005_merge_20210529_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='preparation',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='votes',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
